# Generated by Django 5.2.15 on 2026-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('source_type', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('author_role', models.CharField(blank=True, max_length=255, null=True)),
                ('author_company', models.CharField(blank=True, max_length=255, null=True)),
                ('author_headline', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('subtopic', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('post_type', models.CharField(blank=True, max_length=100, null=True)),
                ('post_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_type', models.CharField(blank=True, max_length=100, null=True)),
                ('formality_level', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_summary', models.TextField(blank=True, null=True)),
                ('latest_message', models.TextField(blank=True, null=True)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reply_goal', models.CharField(default='engage', max_length=100)),
                ('reply_style', models.CharField(default='professional', max_length=100)),
                ('reply_length', models.CharField(default='medium', max_length=50)),
                ('emoji_level', models.IntegerField(default=50)),
                ('creativity_level', models.IntegerField(default=50)),
                ('professional_reply', models.TextField(blank=True, null=True)),
                ('friendly_reply', models.TextField(blank=True, null=True)),
                ('engaging_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
